/**
 * B3 — TODO aggregator (Layer 3 / script-only, NO AI).
 *
 * Two passes over the vault:
 *
 *   1. Collect every unchecked task `- [ ]` (also `* [ ]` and `+ [ ]`) across
 *      all Markdown notes. Keep the source file path and line number so we can
 *      render a clickable backlink.
 *   2. Collect every file whose YAML frontmatter contains tag `notdone`, or a
 *      body tag `#notdone`. These are whole notes the user has flagged as
 *      pending.
 *
 * The result is written to a single configurable note (default: `todo.md` at
 * the vault root). We embed a generated marker so user edits between the
 * markers are overwritten safely, while text outside the markers is preserved.
 *
 * No LLM is invoked. Cost: zero tokens.
 */
import type { App, TFile } from "obsidian";

export interface TodoAggregatorOptions {
	outputPath: string;
	/** Glob patterns to ignore (e.g. ["templates/**", ".obsidian/**"]). */
	ignore?: string[];
}

export interface UncheckedTask {
	file: string;
	line: number;
	text: string;
	heading: string | null;
}

export interface NotDoneNote {
	file: string;
	title: string;
}

const MARKER_START = "<!-- jcode-todo:start (auto-generated, do not edit) -->";
const MARKER_END = "<!-- jcode-todo:end -->";

const UNCHECKED_RE = /^(\s*)[-*+]\s+\[\s\]\s+(.+)$/;
const HEADING_RE = /^(#{1,6})\s+(.+)$/;
const BODY_TAG_RE = /(^|\s)#notdone(\b|$)/;

export class TodoAggregator {
	constructor(private app: App, private opts: TodoAggregatorOptions) {}

	async run(): Promise<{ tasks: UncheckedTask[]; notes: NotDoneNote[]; outputPath: string }> {
		const files = this.app.vault.getMarkdownFiles();
		const tasks: UncheckedTask[] = [];
		const notes: NotDoneNote[] = [];
		const ignore = compileIgnore(this.opts.ignore ?? []);

		for (const f of files) {
			if (ignore(f.path)) continue;
			if (this.opts.outputPath && f.path === this.opts.outputPath) continue;

			const isTaggedNotDone = this.fileHasNotDoneTag(f);
			if (isTaggedNotDone) {
				notes.push({ file: f.path, title: f.basename });
			}

			let content: string;
			try {
				content = await this.app.vault.cachedRead(f);
			} catch {
				continue;
			}

			const lines = content.split("\n");
			let currentHeading: string | null = null;
			for (let i = 0; i < lines.length; i++) {
				const line = lines[i];
				const h = HEADING_RE.exec(line);
				if (h) {
					currentHeading = h[2].trim();
					continue;
				}
				const m = UNCHECKED_RE.exec(line);
				if (m) {
					tasks.push({
						file: f.path,
						line: i + 1,
						text: m[2].trim(),
						heading: currentHeading,
					});
				}
			}
		}

		const md = renderMarkdown(tasks, notes);
		await this.writeOutput(md);
		return { tasks, notes, outputPath: this.opts.outputPath };
	}

	private fileHasNotDoneTag(f: TFile): boolean {
		const cache = this.app.metadataCache.getFileCache(f);
		if (!cache) return false;

		const fm = cache.frontmatter;
		if (fm && fm.tags) {
			const tags = fm.tags;
			if (Array.isArray(tags)) {
				if (tags.some((t) => String(t) === "notdone")) return true;
			} else if (typeof tags === "string") {
				if (tags === "notdone") return true;
			}
		}

		if (cache.tags) {
			for (const t of cache.tags) {
				if (t?.tag === "#notdone") return true;
			}
		}
		return false;
	}

	private async writeOutput(body: string) {
		const path = this.opts.outputPath;
		const existing = this.app.vault.getAbstractFileByPath(path);
		const generated = wrap(body);

		if (existing && "stat" in existing) {
			const file = existing as TFile;
			const old = await this.app.vault.read(file);
			const next = replaceManaged(old, generated);
			if (next !== old) {
				await this.app.vault.modify(file, next);
			}
			return;
		}

		// New file: write a tiny header so users see what it is.
		const initial = `# TODO (auto-generated by jcode-obsidian)\n\n${generated}\n`;
		await this.app.vault.create(path, initial);
	}
}

function compileIgnore(patterns: string[]): (path: string) => boolean {
	if (patterns.length === 0) return () => false;
	const regexes = patterns.map((p) => globToRegex(p));
	return (path) => regexes.some((r) => r.test(path));
}

function globToRegex(glob: string): RegExp {
	// Minimal glob → regex: ** = any chars, * = any chars except /, ? = single char.
	const escaped = glob
		.replace(/[.+^${}()|[\]\\]/g, "\\$&")
		.replace(/\*\*/g, "::DOUBLE::")
		.replace(/\*/g, "[^/]*")
		.replace(/::DOUBLE::/g, ".*")
		.replace(/\?/g, ".");
	return new RegExp(`^${escaped}$`);
}

export function renderMarkdown(tasks: UncheckedTask[], notes: NotDoneNote[]): string {
	const lines: string[] = [];
	lines.push(`> Generated: ${new Date().toISOString()}`);
	lines.push(`> Tasks: ${tasks.length} · Notes tagged #notdone: ${notes.length}`);
	lines.push("");

	// Group tasks by file for readability.
	const byFile = new Map<string, UncheckedTask[]>();
	for (const t of tasks) {
		const arr = byFile.get(t.file) ?? [];
		arr.push(t);
		byFile.set(t.file, arr);
	}

	lines.push("## Unchecked tasks");
	if (byFile.size === 0) {
		lines.push("");
		lines.push("_(none)_");
	}
	for (const [file, items] of Array.from(byFile.entries()).sort()) {
		lines.push("");
		lines.push(`### [[${file}]]`);
		for (const t of items) {
			const headingHint = t.heading ? ` _(${t.heading})_` : "";
			lines.push(`- [ ] ${t.text} ([line ${t.line}](${encodeLink(file)}#L${t.line}))${headingHint}`);
		}
	}

	lines.push("");
	lines.push("## Notes tagged `#notdone`");
	if (notes.length === 0) {
		lines.push("");
		lines.push("_(none)_");
	} else {
		for (const n of notes.sort((a, b) => a.title.localeCompare(b.title))) {
			lines.push(`- [[${n.file}|${n.title}]]`);
		}
	}

	return lines.join("\n");
}

function encodeLink(p: string): string {
	return p.split("/").map(encodeURIComponent).join("/");
}

function wrap(body: string): string {
	return `${MARKER_START}\n${body}\n${MARKER_END}`;
}

function replaceManaged(existing: string, replacement: string): string {
	const start = existing.indexOf(MARKER_START);
	const end = existing.indexOf(MARKER_END);
	if (start === -1 || end === -1 || end < start) {
		// File exists but has no managed block; append one.
		return `${existing.trimEnd()}\n\n${replacement}\n`;
	}
	const before = existing.slice(0, start);
	const after = existing.slice(end + MARKER_END.length);
	return `${before}${replacement}${after}`;
}

// Exposed for tests.
export const _internals = {
	UNCHECKED_RE,
	HEADING_RE,
	BODY_TAG_RE,
	renderMarkdown,
	replaceManaged,
	globToRegex,
	wrap,
	MARKER_START,
	MARKER_END,
};
